### ISSUE TITLE
NPE during .mdkmodel export

### ISSUE THREAD

**Issue by garamibence** [IncQueryLabs/mdk#7]
In Cameo Systems Modeler 2021x -> MDK menu -> MDK JSON -> Export entire (primary) model to .mdkmodel file
Instead of appearing a choose folder dialog internal error occured.

```
Tue Jun 15 10:52:18 CEST 2021
Error count: 2
java.lang.NullPointerException
	at com.jidesoft.plaf.basic.BasicFolderChooserUI.isLink(Unknown Source)
	at com.jidesoft.plaf.basic.BasicFolderChooserUI.isFileSystem(Unknown Source)
	at com.jidesoft.plaf.basic.BasicFolderChooserUI.getTreePathForFile(Unknown Source)
	at com.jidesoft.plaf.basic.BasicFolderChooserUI.ensureFileIsVisible(Unknown Source)
	at com.jidesoft.plaf.basic.BasicFolderChooserUI.access$100(Unknown Source)
	at com.jidesoft.plaf.basic.BasicFolderChooserUI$FolderChooserPropertyChangeListener.propertyChange(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8728)
	at java.desktop/javax.swing.JFileChooser.setCurrentDirectory(JFileChooser.java:595)
	at java.desktop/javax.swing.JFileChooser.<init>(JFileChooser.java:349)
	at java.desktop/javax.swing.JFileChooser.<init>(JFileChooser.java:295)
	at com.jidesoft.swing.FolderChooser.<init>(Unknown Source)
	at gov.nasa.jpl.mbee.mdk.actions.ExportToJsonRecursivelyAction.chooseFolder(ExportToJsonRecursivelyAction.java:124)
	at gov.nasa.jpl.mbee.mdk.actions.ExportToJsonRecursivelyAction.actionPerformed(ExportToJsonRecursivelyAction.java:106)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at com.jidesoft.plaf.vsnet.VsnetMenuItemUI.doClick(Unknown Source)
	at com.jidesoft.plaf.vsnet.VsnetMenuItemUI$MouseInputHandler.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at com.nomagic.utils.EventTracker.dispatchEvent(EventTracker.java:31)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

User information:
    Registered to: CATIA Magic EAP
    Profile: 0
    Key ID: custom
System information:
    JVM:
        Name: OpenJDK 64-Bit Server VM;
        Version: 11;
        Vendor: Oracle Corporation;
    OS:
        Name: Windows 10;
        Architecture: amd64;
        Version: 10.0;
        Locale: magyar (Magyarország);
MagicDraw Version:
Cameo Systems Modeler 2021x
Version: Commercial with expiration
Edition: Enterprise
License: Seat
Build: 20201221_2033-ee946a35
Registered to: CATIA Magic EAP
Expires at: December 1, 2021

Cameo Requirements Modeler 2021x Plugin
Version: Evaluation
Build: 20201221_2016-ee946a35
Expires at: December 1, 2021

Cameo Simulation Toolkit 2021x Plugin
Version: Evaluation
Build: 20201221_2011-ee946a35
Expires at: December 1, 2021

Merge 2021x Plugin
Version: Evaluation
Build: 20201221_2033-ee946a35
Expires at: December 1, 2021

SysML 2021x Plugin
Version: Evaluation
Build: 20201221_2028-ee946a35
Expires at: December 1, 2021

Third Party Plugins:
Model Development Kit ${human.version} (NASA / Jet Propulsion Laboratory / Caltech)
Model Development Kit 4.4.4-SNAPSHOT (NASA / Jet Propulsion Laboratory / Caltech)
```

**Comment by abelhegedus** [comment]
You should use Cameo 19.0 SP4 instead.
